# Generated by Django 3.2.3 on 2021-05-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='Company',
            new_name='company',
        ),
    ]
